In [1]:
# GRADED FUNCTION: basic_sigmoid

import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1.0/(1+math.exp(-x))
    ### END CODE HERE ###
    
    return s

In [2]:
basic_sigmoid(3)

0.9525741268224334

In [3]:
x = [1, 2, 3]
basic_sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [8]:
import numpy as np
x = [1, 2, 3]
print(np.exp(x))
explist = np.exp(x)
print(explist)

[ 2.71828183  7.3890561  20.08553692]
[ 2.71828183  7.3890561  20.08553692]


In [10]:
addlist = np.array(x) + 3
print(addlist, np.shape(addlist))

[4 5 6] (3,)


In [15]:
def sigmoid_deravatives(x):
    s = 1.0/(1+np.exp(-x))
    ds = s*(1-s)
    return ds

In [16]:
x = [1, 2, 3]
print(sigmoid_deravatives(np.array(x)))


[0.19661193 0.10499359 0.04517666]


In [30]:
def image2vector(image):
    v = image.reshape(image.shape[0]*image.shape[1].image.shape[2], 1)
    return v

In [46]:
print(np.array([1, 2, 3]).size)
print(np.array([1, 2, 3]).shape)
print(np.array([[1, 2, 3], [4, 5, 6]]).size)
print(np.array([[1, 2, 3], [4, 5, 6]]).shape)

image = np.array(
[[[1, 2, 3],
  [4, 5, 6]],
 
[[7, 8, 9],
  [10, 11, 12]],
    
 [[13, 14, 15],
 [16, 17, 18]]
    
])
print(image.shape)
print((image2vector(image)))

3
(3,)
6
(2, 3)
(3, 2, 3)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]]


In [37]:
# GRADED FUNCTION: image2vector
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
    ### END CODE HERE ###
    
    return v

In [39]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print(image.shape)
print ("image2vector(image) = " + str(image2vector(image)))

(3, 3, 2)
image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [55]:
def normalize(x):
    x_norm = np.linalg.norm(x, ord=2, axis=1, keepdims=True)
    print(x_norm)
    print(x_norm.shape)
    x = x/x_norm
    print(x.shape)
    return x

In [56]:
x = np.array(([0, 3, 5],
        [-1, 2, 4]))
print(normalize(x))

[[5.83095189]
 [4.58257569]]
(2, 1)
(2, 3)
[[ 0.          0.51449576  0.85749293]
 [-0.21821789  0.43643578  0.87287156]]


In [66]:
def softmax(x):
    print("Shape of Given matrix {}".format(x.shape))
    x_exp = np.exp(x)
    print("shape of exp matrix {}".format(x_exp.shape))
    print("Content of exp matrix : {}".format(x_exp))
    
    x_sum = np.sum(x, axis=1, keepdims=True)
    print("Shape of sum matrix {}".format(x_sum.shape))
    print("Sum matrix: {}".format(x_sum))
    
    x = x_exp/x_sum
    print("Shape of resulting matrix {}".format(x))
    return x


In [67]:
x = np.array(([3, 4, 2, 6],
             [6, 1, 5, 7]))
print("Resulting softmax: {}".format(softmax(x)))

Shape of Given matrix (2, 4)
shape of exp matrix (2, 4)
Content of exp matrix : [[  20.08553692   54.59815003    7.3890561   403.42879349]
 [ 403.42879349    2.71828183  148.4131591  1096.63315843]]
Shape of sum matrix (2, 1)
Sum matrix: [[15]
 [19]]
Shape of resulting matrix [[ 1.33903579  3.63987667  0.49260374 26.8952529 ]
 [21.23309439  0.14306746  7.8112189  57.71753465]]
Resulting softmax: [[ 1.33903579  3.63987667  0.49260374 26.8952529 ]
 [21.23309439  0.14306746  7.8112189  57.71753465]]


In [85]:
import time

x1 = [2, 5, 7, 3, 9]
x2 = [1, 3, 4, 2, 6]

#Dot product
dot = 0
tic = time.process_time()
for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()

print("Dot Product: {} ==> Time taken for this {} ms".format(dot, str(1000*(toc-tic))))

#outer prdouct
tic = time.process_time()
outer = np.zeros((len(x1), len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i][j] = x1[i] * x2[j]
toc = time.process_time()

print("Outer product:\n {} \n ==> Time take for this {} ms".format(outer, str(1000*(toc-tic))))


#Element wise mututiplication.

tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()

print("Element wise mutiplication : \n {} \n ===> Time taken for this {} ms".format(mul, str(1000*(toc-tic))))
        


Dot Product: 105 ==> Time taken for this 0.0 ms
Outer product:
 [[ 2.  6.  8.  4. 12.]
 [ 5. 15. 20. 10. 30.]
 [ 7. 21. 28. 14. 42.]
 [ 3.  9. 12.  6. 18.]
 [ 9. 27. 36. 18. 54.]] 
 ==> Time take for this 0.0 ms
Element wise mutiplication : 
 [ 2. 15. 28.  6. 54.] 
 ===> Time taken for this 0.0 ms


In [89]:
#Now use vectoration for above three multiplicon:
tic = time.process_time()
dot = np.dot(x1, x2)
toc = time.process_time()
print("Dot product using vectorization : {} ===> Time taken : {} ms".format(dot, str(1000*(toc- tic))))


tic = time.process_time()
outer = np.outer(x1, x2)
toc = time.process_time()
print("Outer matrix mutipliction using numpay :\n {} \n time taken is {} ms".format(outer, str(1000*(toc-tic))))


tic = time.process_time()
mul = np.multiply(x1, x2)
toc = time.process_time()
print("Element wise mutipliction using np.mutiply: \n {} \n ==> Time taken {}".format(mul, str(1000*(toc-tic))))


Dot product using vectorization : 105 ===> Time taken : 0.0 ms
Outer matrix mutipliction using numpay :
 [[ 2  6  8  4 12]
 [ 5 15 20 10 30]
 [ 7 21 28 14 42]
 [ 3  9 12  6 18]
 [ 9 27 36 18 54]] 
 time taken is 0.0 ms
Element wise mutipliction using np.mutiply: 
 [ 2 15 28  6 54] 
 ==> Time taken 0.0


In [95]:
#Loss function:
def L1_lossfunction(yhat, y):
    diff = np.abs(yhat-y)
    loss = np.sum(diff)
    return loss
def L2_lossfunction(yhat, y):
    return np.sum(np.power((yhat-y), 2))
    

In [96]:
yhat = np.array([.9, 0.2, 0.1, 0.4, 0.9])
y = np.array([1, 0, 0, 1, 1])
print("L1 =" + str(L1_lossfunction(yhat, y)))
print("L2 =" + str(L2_lossfunction(yhat, y)))

L1 =1.1
L2 =0.43
