In [1]:
import numpy as np

In [2]:
#calcuate sigmoid function

def sigmoid(x):
    return (1.0/(1+np.exp(-x)))


In [3]:
x= np.array([1, 2, 3])
print("Sigmoid:\n {} \n shape: {}".format(sigmoid(x), sigmoid(x).shape))

Sigmoid:
 [0.73105858 0.88079708 0.95257413] 
 shape: (3,)


In [11]:
#Deratvatives of sigmoid
def sigmoid_deravaties(x):
    s = (1.0/(1+np.exp(x)))
    print(s, s.shape)
    return (s *(1-s))

In [12]:
print(sigmoid_deravaties(x))

[0.26894142 0.11920292 0.04742587] (3,)
[0.19661193 0.10499359 0.04517666]


In [ ]:
#normalize
def normalize(x):
    
    x_norm = np.linalg.norm(x, org=2, axis=1, keepdims=True)
    return x/x_norm

In [ ]:
x= np.array(([2, 3, 1], [7,3, 2]))
print(x.shape)
print(normalize(x))

In [ ]:
def image2vector(image):
    x = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    return x

In [ ]:
image = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    
    [
        [7, 8, 9]
        [10, 11, 12]
        
    ]
    [
        []
    ]
])